name: CI/CD

on:
  push:
    branches: main
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - .github/workflows/cicd.yml
      - integration-template.yml
      - Makefile
      - '**/*.sh'
      - '**/*.crt'
      - '**/*.key'

jobs:
  test:
    name: Run automated tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Cache AWS SAM installation
        id: cache-aws-sam
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/sam
          key: aws-sam

      - name: Install AWS SAM
        if: steps.cache-aws-sam.outputs.cache-hit != 'true'
        run: ./scripts/install-aws-sam.sh

      - name: Run the tests
        run: go test ./...
